platform :ios, '11.0'
inhibit_all_warnings!

pod 'SwiftLint'
pod 'SwiftFormat/CLI'

target 'Shopping-Cart' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Kingfisher', '~> 5.0'
  pod "KRProgressHUD"
end

target 'Components' do
end

target 'Shared' do
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end